# Generated by Django 4.2.16 on 2024-11-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
